name: 'Get parameter'

inputs:
  message:
    description: 'Message to parse. Defaults to head commit message'
    required: false
    default: ${{ github.event.head_commit.message }}
  param-0:
    description: 'Name of the first parameter to get'
    required: true
  param-1:
    description: 'Name of the second parameter to get'
    required: false
  param-2:
    description: 'Name of the third parameter to get'
    required: false
  param-3:
    description: 'Name of the fourth parameter to get'
    required: false
outputs:
  param-0:
    description: "Value of first parameter to get"
    value: ${{ steps.value-0.outputs.value }}
  param-1:
    description: "Value of second parameter to get"
    value: ${{ steps.value-1.outputs.value }}
  param-2:
    description: "Value of third parameter to get"
    value: ${{ steps.value-2.outputs.value }}
  param-3:
    description: "Value of fourth parameter to get"
    value: ${{ steps.value-3.outputs.value }}

runs:
  using: 'node20'
  main: 'dist/index.js'
